// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/downloader.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<ProgressUpdate> dco_decode_StreamSink_progress_update_Sse(
      dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BilibiliQrLogin dco_decode_bilibili_qr_login(dynamic raw);

  @protected
  BilibiliQrLoginPoll dco_decode_bilibili_qr_login_poll(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DownloadOptions dco_decode_box_autoadd_download_options(dynamic raw);

  @protected
  MediaCollection dco_decode_box_autoadd_media_collection(dynamic raw);

  @protected
  MediaSource dco_decode_box_autoadd_media_source(dynamic raw);

  @protected
  RequestContext dco_decode_box_autoadd_request_context(dynamic raw);

  @protected
  DownloadOptions dco_decode_download_options(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  HeaderEntry dco_decode_header_entry(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<HeaderEntry> dco_decode_list_header_entry(dynamic raw);

  @protected
  List<MediaCandidate> dco_decode_list_media_candidate(dynamic raw);

  @protected
  List<MediaCollectionEntry> dco_decode_list_media_collection_entry(
      dynamic raw);

  @protected
  List<MediaSubtitleTrack> dco_decode_list_media_subtitle_track(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  MediaCandidate dco_decode_media_candidate(dynamic raw);

  @protected
  MediaCollection dco_decode_media_collection(dynamic raw);

  @protected
  MediaCollectionEntry dco_decode_media_collection_entry(dynamic raw);

  @protected
  MediaInspectionResult dco_decode_media_inspection_result(dynamic raw);

  @protected
  MediaSource dco_decode_media_source(dynamic raw);

  @protected
  MediaSubtitleTrack dco_decode_media_subtitle_track(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  MediaCollection? dco_decode_opt_box_autoadd_media_collection(dynamic raw);

  @protected
  ProgressUpdate dco_decode_progress_update(dynamic raw);

  @protected
  RequestContext dco_decode_request_context(dynamic raw);

  @protected
  SubtitleMode dco_decode_subtitle_mode(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<ProgressUpdate> sse_decode_StreamSink_progress_update_Sse(
      SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BilibiliQrLogin sse_decode_bilibili_qr_login(SseDeserializer deserializer);

  @protected
  BilibiliQrLoginPoll sse_decode_bilibili_qr_login_poll(
      SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DownloadOptions sse_decode_box_autoadd_download_options(
      SseDeserializer deserializer);

  @protected
  MediaCollection sse_decode_box_autoadd_media_collection(
      SseDeserializer deserializer);

  @protected
  MediaSource sse_decode_box_autoadd_media_source(SseDeserializer deserializer);

  @protected
  RequestContext sse_decode_box_autoadd_request_context(
      SseDeserializer deserializer);

  @protected
  DownloadOptions sse_decode_download_options(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  HeaderEntry sse_decode_header_entry(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<HeaderEntry> sse_decode_list_header_entry(SseDeserializer deserializer);

  @protected
  List<MediaCandidate> sse_decode_list_media_candidate(
      SseDeserializer deserializer);

  @protected
  List<MediaCollectionEntry> sse_decode_list_media_collection_entry(
      SseDeserializer deserializer);

  @protected
  List<MediaSubtitleTrack> sse_decode_list_media_subtitle_track(
      SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  MediaCandidate sse_decode_media_candidate(SseDeserializer deserializer);

  @protected
  MediaCollection sse_decode_media_collection(SseDeserializer deserializer);

  @protected
  MediaCollectionEntry sse_decode_media_collection_entry(
      SseDeserializer deserializer);

  @protected
  MediaInspectionResult sse_decode_media_inspection_result(
      SseDeserializer deserializer);

  @protected
  MediaSource sse_decode_media_source(SseDeserializer deserializer);

  @protected
  MediaSubtitleTrack sse_decode_media_subtitle_track(
      SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  MediaCollection? sse_decode_opt_box_autoadd_media_collection(
      SseDeserializer deserializer);

  @protected
  ProgressUpdate sse_decode_progress_update(SseDeserializer deserializer);

  @protected
  RequestContext sse_decode_request_context(SseDeserializer deserializer);

  @protected
  SubtitleMode sse_decode_subtitle_mode(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_progress_update_Sse(
      RustStreamSink<ProgressUpdate> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bilibili_qr_login(
      BilibiliQrLogin self, SseSerializer serializer);

  @protected
  void sse_encode_bilibili_qr_login_poll(
      BilibiliQrLoginPoll self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_download_options(
      DownloadOptions self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_media_collection(
      MediaCollection self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_media_source(
      MediaSource self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_request_context(
      RequestContext self, SseSerializer serializer);

  @protected
  void sse_encode_download_options(
      DownloadOptions self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_header_entry(HeaderEntry self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_header_entry(
      List<HeaderEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_media_candidate(
      List<MediaCandidate> self, SseSerializer serializer);

  @protected
  void sse_encode_list_media_collection_entry(
      List<MediaCollectionEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_media_subtitle_track(
      List<MediaSubtitleTrack> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_media_candidate(
      MediaCandidate self, SseSerializer serializer);

  @protected
  void sse_encode_media_collection(
      MediaCollection self, SseSerializer serializer);

  @protected
  void sse_encode_media_collection_entry(
      MediaCollectionEntry self, SseSerializer serializer);

  @protected
  void sse_encode_media_inspection_result(
      MediaInspectionResult self, SseSerializer serializer);

  @protected
  void sse_encode_media_source(MediaSource self, SseSerializer serializer);

  @protected
  void sse_encode_media_subtitle_track(
      MediaSubtitleTrack self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_media_collection(
      MediaCollection? self, SseSerializer serializer);

  @protected
  void sse_encode_progress_update(
      ProgressUpdate self, SseSerializer serializer);

  @protected
  void sse_encode_request_context(
      RequestContext self, SseSerializer serializer);

  @protected
  void sse_encode_subtitle_mode(SubtitleMode self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;
}
