// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/downloader.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiDownloaderInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -1942244692;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'rust_lib_segmeris',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  Stream<ProgressUpdate> crateApiDownloaderDownloadMediaRun(
      {required String pageUrl,
      required String mediaUrl,
      String? audioUrl,
      required String output,
      required int concurrency,
      required int retries,
      required int videoBitrate,
      required int audioBitrate,
      required bool keepTemp});

  Stream<ProgressUpdate> crateApiDownloaderDownloadMediaWithContext(
      {required String pageUrl,
      required String mediaUrl,
      String? audioUrl,
      required String output,
      required int concurrency,
      required int retries,
      required int videoBitrate,
      required int audioBitrate,
      required bool keepTemp,
      required RequestContext requestContext});

  Stream<ProgressUpdate> crateApiDownloaderHls2Mp4Run(
      {required String url,
      required int concurrency,
      required String output,
      required int retries,
      required int videoBitrate,
      required int audioBitrate,
      required bool keepTemp});

  Future<void> crateApiDownloaderInitApp();

  Future<MediaInspectionResult> crateApiDownloaderInspectMediaFromUrl(
      {required String url});

  Future<MediaInspectionResult> crateApiDownloaderInspectMediaWithContext(
      {required String url, required RequestContext requestContext});

  Future<RequestContext> crateApiDownloaderRequestContextDefault();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Stream<ProgressUpdate> crateApiDownloaderDownloadMediaRun(
      {required String pageUrl,
      required String mediaUrl,
      String? audioUrl,
      required String output,
      required int concurrency,
      required int retries,
      required int videoBitrate,
      required int audioBitrate,
      required bool keepTemp}) {
    final sink = RustStreamSink<ProgressUpdate>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_StreamSink_progress_update_Sse(sink, serializer);
        sse_encode_String(pageUrl, serializer);
        sse_encode_String(mediaUrl, serializer);
        sse_encode_opt_String(audioUrl, serializer);
        sse_encode_String(output, serializer);
        sse_encode_i_32(concurrency, serializer);
        sse_encode_i_32(retries, serializer);
        sse_encode_i_32(videoBitrate, serializer);
        sse_encode_i_32(audioBitrate, serializer);
        sse_encode_bool(keepTemp, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDownloaderDownloadMediaRunConstMeta,
      argValues: [
        sink,
        pageUrl,
        mediaUrl,
        audioUrl,
        output,
        concurrency,
        retries,
        videoBitrate,
        audioBitrate,
        keepTemp
      ],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiDownloaderDownloadMediaRunConstMeta =>
      const TaskConstMeta(
        debugName: "download_media_run",
        argNames: [
          "sink",
          "pageUrl",
          "mediaUrl",
          "audioUrl",
          "output",
          "concurrency",
          "retries",
          "videoBitrate",
          "audioBitrate",
          "keepTemp"
        ],
      );

  @override
  Stream<ProgressUpdate> crateApiDownloaderDownloadMediaWithContext(
      {required String pageUrl,
      required String mediaUrl,
      String? audioUrl,
      required String output,
      required int concurrency,
      required int retries,
      required int videoBitrate,
      required int audioBitrate,
      required bool keepTemp,
      required RequestContext requestContext}) {
    final sink = RustStreamSink<ProgressUpdate>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_StreamSink_progress_update_Sse(sink, serializer);
        sse_encode_String(pageUrl, serializer);
        sse_encode_String(mediaUrl, serializer);
        sse_encode_opt_String(audioUrl, serializer);
        sse_encode_String(output, serializer);
        sse_encode_i_32(concurrency, serializer);
        sse_encode_i_32(retries, serializer);
        sse_encode_i_32(videoBitrate, serializer);
        sse_encode_i_32(audioBitrate, serializer);
        sse_encode_bool(keepTemp, serializer);
        sse_encode_box_autoadd_request_context(requestContext, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDownloaderDownloadMediaWithContextConstMeta,
      argValues: [
        sink,
        pageUrl,
        mediaUrl,
        audioUrl,
        output,
        concurrency,
        retries,
        videoBitrate,
        audioBitrate,
        keepTemp,
        requestContext
      ],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiDownloaderDownloadMediaWithContextConstMeta =>
      const TaskConstMeta(
        debugName: "download_media_with_context",
        argNames: [
          "sink",
          "pageUrl",
          "mediaUrl",
          "audioUrl",
          "output",
          "concurrency",
          "retries",
          "videoBitrate",
          "audioBitrate",
          "keepTemp",
          "requestContext"
        ],
      );

  @override
  Stream<ProgressUpdate> crateApiDownloaderHls2Mp4Run(
      {required String url,
      required int concurrency,
      required String output,
      required int retries,
      required int videoBitrate,
      required int audioBitrate,
      required bool keepTemp}) {
    final sink = RustStreamSink<ProgressUpdate>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_StreamSink_progress_update_Sse(sink, serializer);
        sse_encode_String(url, serializer);
        sse_encode_i_32(concurrency, serializer);
        sse_encode_String(output, serializer);
        sse_encode_i_32(retries, serializer);
        sse_encode_i_32(videoBitrate, serializer);
        sse_encode_i_32(audioBitrate, serializer);
        sse_encode_bool(keepTemp, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDownloaderHls2Mp4RunConstMeta,
      argValues: [
        sink,
        url,
        concurrency,
        output,
        retries,
        videoBitrate,
        audioBitrate,
        keepTemp
      ],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiDownloaderHls2Mp4RunConstMeta =>
      const TaskConstMeta(
        debugName: "hls2mp4_run",
        argNames: [
          "sink",
          "url",
          "concurrency",
          "output",
          "retries",
          "videoBitrate",
          "audioBitrate",
          "keepTemp"
        ],
      );

  @override
  Future<void> crateApiDownloaderInitApp() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDownloaderInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDownloaderInitAppConstMeta => const TaskConstMeta(
        debugName: "init_app",
        argNames: [],
      );

  @override
  Future<MediaInspectionResult> crateApiDownloaderInspectMediaFromUrl(
      {required String url}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(url, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_media_inspection_result,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDownloaderInspectMediaFromUrlConstMeta,
      argValues: [url],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDownloaderInspectMediaFromUrlConstMeta =>
      const TaskConstMeta(
        debugName: "inspect_media_from_url",
        argNames: ["url"],
      );

  @override
  Future<MediaInspectionResult> crateApiDownloaderInspectMediaWithContext(
      {required String url, required RequestContext requestContext}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(url, serializer);
        sse_encode_box_autoadd_request_context(requestContext, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_media_inspection_result,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDownloaderInspectMediaWithContextConstMeta,
      argValues: [url, requestContext],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDownloaderInspectMediaWithContextConstMeta =>
      const TaskConstMeta(
        debugName: "inspect_media_with_context",
        argNames: ["url", "requestContext"],
      );

  @override
  Future<RequestContext> crateApiDownloaderRequestContextDefault() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_request_context,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDownloaderRequestContextDefaultConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDownloaderRequestContextDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "request_context_default",
        argNames: [],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<ProgressUpdate> dco_decode_StreamSink_progress_update_Sse(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  RequestContext dco_decode_box_autoadd_request_context(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_request_context(raw);
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  HeaderEntry dco_decode_header_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return HeaderEntry(
      name: dco_decode_String(arr[0]),
      value: dco_decode_String(arr[1]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<HeaderEntry> dco_decode_list_header_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_header_entry).toList();
  }

  @protected
  List<MediaCandidate> dco_decode_list_media_candidate(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_media_candidate).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MediaCandidate dco_decode_media_candidate(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 18)
      throw Exception('unexpected arr length: expect 18 but see ${arr.length}');
    return MediaCandidate(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      extractor: dco_decode_String(arr[2]),
      pageUrl: dco_decode_String(arr[3]),
      mediaUrl: dco_decode_String(arr[4]),
      audioUrl: dco_decode_opt_String(arr[5]),
      container: dco_decode_String(arr[6]),
      protocol: dco_decode_String(arr[7]),
      mimeType: dco_decode_String(arr[8]),
      qualityLabel: dco_decode_String(arr[9]),
      width: dco_decode_i_32(arr[10]),
      height: dco_decode_i_32(arr[11]),
      requiresFfmpeg: dco_decode_bool(arr[12]),
      score: dco_decode_i_32(arr[13]),
      segmentCount: dco_decode_i_32(arr[14]),
      durationSeconds: dco_decode_f_64(arr[15]),
      primary: dco_decode_bool(arr[16]),
      reason: dco_decode_String(arr[17]),
    );
  }

  @protected
  MediaInspectionResult dco_decode_media_inspection_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return MediaInspectionResult(
      pageUrl: dco_decode_String(arr[0]),
      pageTitle: dco_decode_String(arr[1]),
      extractor: dco_decode_String(arr[2]),
      candidates: dco_decode_list_media_candidate(arr[3]),
      warnings: dco_decode_list_String(arr[4]),
      authRequired: dco_decode_bool(arr[5]),
      challengeReason: dco_decode_String(arr[6]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  ProgressUpdate dco_decode_progress_update(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ProgressUpdate(
      message: dco_decode_String(arr[0]),
      progress: dco_decode_f_64(arr[1]),
      error: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  RequestContext dco_decode_request_context(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return RequestContext(
      userAgent: dco_decode_String(arr[0]),
      referer: dco_decode_String(arr[1]),
      origin: dco_decode_String(arr[2]),
      cookie: dco_decode_String(arr[3]),
      headers: dco_decode_list_header_entry(arr[4]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<ProgressUpdate> sse_decode_StreamSink_progress_update_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  RequestContext sse_decode_box_autoadd_request_context(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_request_context(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  HeaderEntry sse_decode_header_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_value = sse_decode_String(deserializer);
    return HeaderEntry(name: var_name, value: var_value);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<HeaderEntry> sse_decode_list_header_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <HeaderEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_header_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<MediaCandidate> sse_decode_list_media_candidate(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MediaCandidate>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_media_candidate(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MediaCandidate sse_decode_media_candidate(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_extractor = sse_decode_String(deserializer);
    var var_pageUrl = sse_decode_String(deserializer);
    var var_mediaUrl = sse_decode_String(deserializer);
    var var_audioUrl = sse_decode_opt_String(deserializer);
    var var_container = sse_decode_String(deserializer);
    var var_protocol = sse_decode_String(deserializer);
    var var_mimeType = sse_decode_String(deserializer);
    var var_qualityLabel = sse_decode_String(deserializer);
    var var_width = sse_decode_i_32(deserializer);
    var var_height = sse_decode_i_32(deserializer);
    var var_requiresFfmpeg = sse_decode_bool(deserializer);
    var var_score = sse_decode_i_32(deserializer);
    var var_segmentCount = sse_decode_i_32(deserializer);
    var var_durationSeconds = sse_decode_f_64(deserializer);
    var var_primary = sse_decode_bool(deserializer);
    var var_reason = sse_decode_String(deserializer);
    return MediaCandidate(
        id: var_id,
        title: var_title,
        extractor: var_extractor,
        pageUrl: var_pageUrl,
        mediaUrl: var_mediaUrl,
        audioUrl: var_audioUrl,
        container: var_container,
        protocol: var_protocol,
        mimeType: var_mimeType,
        qualityLabel: var_qualityLabel,
        width: var_width,
        height: var_height,
        requiresFfmpeg: var_requiresFfmpeg,
        score: var_score,
        segmentCount: var_segmentCount,
        durationSeconds: var_durationSeconds,
        primary: var_primary,
        reason: var_reason);
  }

  @protected
  MediaInspectionResult sse_decode_media_inspection_result(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pageUrl = sse_decode_String(deserializer);
    var var_pageTitle = sse_decode_String(deserializer);
    var var_extractor = sse_decode_String(deserializer);
    var var_candidates = sse_decode_list_media_candidate(deserializer);
    var var_warnings = sse_decode_list_String(deserializer);
    var var_authRequired = sse_decode_bool(deserializer);
    var var_challengeReason = sse_decode_String(deserializer);
    return MediaInspectionResult(
        pageUrl: var_pageUrl,
        pageTitle: var_pageTitle,
        extractor: var_extractor,
        candidates: var_candidates,
        warnings: var_warnings,
        authRequired: var_authRequired,
        challengeReason: var_challengeReason);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProgressUpdate sse_decode_progress_update(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_message = sse_decode_String(deserializer);
    var var_progress = sse_decode_f_64(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return ProgressUpdate(
        message: var_message, progress: var_progress, error: var_error);
  }

  @protected
  RequestContext sse_decode_request_context(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_userAgent = sse_decode_String(deserializer);
    var var_referer = sse_decode_String(deserializer);
    var var_origin = sse_decode_String(deserializer);
    var var_cookie = sse_decode_String(deserializer);
    var var_headers = sse_decode_list_header_entry(deserializer);
    return RequestContext(
        userAgent: var_userAgent,
        referer: var_referer,
        origin: var_origin,
        cookie: var_cookie,
        headers: var_headers);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_progress_update_Sse(
      RustStreamSink<ProgressUpdate> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_progress_update,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_request_context(
      RequestContext self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_request_context(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_header_entry(HeaderEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.value, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_header_entry(
      List<HeaderEntry> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_header_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_media_candidate(
      List<MediaCandidate> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_media_candidate(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_media_candidate(
      MediaCandidate self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.extractor, serializer);
    sse_encode_String(self.pageUrl, serializer);
    sse_encode_String(self.mediaUrl, serializer);
    sse_encode_opt_String(self.audioUrl, serializer);
    sse_encode_String(self.container, serializer);
    sse_encode_String(self.protocol, serializer);
    sse_encode_String(self.mimeType, serializer);
    sse_encode_String(self.qualityLabel, serializer);
    sse_encode_i_32(self.width, serializer);
    sse_encode_i_32(self.height, serializer);
    sse_encode_bool(self.requiresFfmpeg, serializer);
    sse_encode_i_32(self.score, serializer);
    sse_encode_i_32(self.segmentCount, serializer);
    sse_encode_f_64(self.durationSeconds, serializer);
    sse_encode_bool(self.primary, serializer);
    sse_encode_String(self.reason, serializer);
  }

  @protected
  void sse_encode_media_inspection_result(
      MediaInspectionResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.pageUrl, serializer);
    sse_encode_String(self.pageTitle, serializer);
    sse_encode_String(self.extractor, serializer);
    sse_encode_list_media_candidate(self.candidates, serializer);
    sse_encode_list_String(self.warnings, serializer);
    sse_encode_bool(self.authRequired, serializer);
    sse_encode_String(self.challengeReason, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_progress_update(
      ProgressUpdate self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
    sse_encode_f_64(self.progress, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_request_context(
      RequestContext self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.userAgent, serializer);
    sse_encode_String(self.referer, serializer);
    sse_encode_String(self.origin, serializer);
    sse_encode_String(self.cookie, serializer);
    sse_encode_list_header_entry(self.headers, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
