// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/downloader.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiDownloaderInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 781274510;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'rust_lib_segmeris',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<BilibiliQrLoginPoll> crateApiDownloaderBilibiliQrLoginPoll(
      {required String key,
      required String cookie,
      required RequestContext requestContext});

  Future<BilibiliQrLogin> crateApiDownloaderBilibiliQrLoginStart(
      {required RequestContext requestContext});

  Stream<ProgressUpdate> crateApiDownloaderDownloadMediaWithContext(
      {required MediaSource source,
      required String output,
      required DownloadOptions options,
      required RequestContext requestContext});

  Future<DownloadOptions> crateApiDownloaderDownloadOptionsDefault();

  Stream<ProgressUpdate> crateApiDownloaderHls2Mp4Run(
      {required String url,
      required int concurrency,
      required String output,
      required int retries,
      required int videoBitrate,
      required int audioBitrate,
      required bool keepTemp});

  Future<void> crateApiDownloaderInitApp();

  Future<MediaInspectionResult> crateApiDownloaderInspectMediaFromUrl(
      {required String url});

  Future<MediaInspectionResult> crateApiDownloaderInspectMediaWithContext(
      {required String url, required RequestContext requestContext});

  Future<MediaSource> crateApiDownloaderMediaSourceDefault();

  Future<RequestContext> crateApiDownloaderRequestContextDefault();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<BilibiliQrLoginPoll> crateApiDownloaderBilibiliQrLoginPoll(
      {required String key,
      required String cookie,
      required RequestContext requestContext}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(key, serializer);
        sse_encode_String(cookie, serializer);
        sse_encode_box_autoadd_request_context(requestContext, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bilibili_qr_login_poll,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDownloaderBilibiliQrLoginPollConstMeta,
      argValues: [key, cookie, requestContext],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDownloaderBilibiliQrLoginPollConstMeta =>
      const TaskConstMeta(
        debugName: "bilibili_qr_login_poll",
        argNames: ["key", "cookie", "requestContext"],
      );

  @override
  Future<BilibiliQrLogin> crateApiDownloaderBilibiliQrLoginStart(
      {required RequestContext requestContext}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_request_context(requestContext, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bilibili_qr_login,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDownloaderBilibiliQrLoginStartConstMeta,
      argValues: [requestContext],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDownloaderBilibiliQrLoginStartConstMeta =>
      const TaskConstMeta(
        debugName: "bilibili_qr_login_start",
        argNames: ["requestContext"],
      );

  @override
  Stream<ProgressUpdate> crateApiDownloaderDownloadMediaWithContext(
      {required MediaSource source,
      required String output,
      required DownloadOptions options,
      required RequestContext requestContext}) {
    final sink = RustStreamSink<ProgressUpdate>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_StreamSink_progress_update_Sse(sink, serializer);
        sse_encode_box_autoadd_media_source(source, serializer);
        sse_encode_String(output, serializer);
        sse_encode_box_autoadd_download_options(options, serializer);
        sse_encode_box_autoadd_request_context(requestContext, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDownloaderDownloadMediaWithContextConstMeta,
      argValues: [sink, source, output, options, requestContext],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiDownloaderDownloadMediaWithContextConstMeta =>
      const TaskConstMeta(
        debugName: "download_media_with_context",
        argNames: ["sink", "source", "output", "options", "requestContext"],
      );

  @override
  Future<DownloadOptions> crateApiDownloaderDownloadOptionsDefault() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_download_options,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDownloaderDownloadOptionsDefaultConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDownloaderDownloadOptionsDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "download_options_default",
        argNames: [],
      );

  @override
  Stream<ProgressUpdate> crateApiDownloaderHls2Mp4Run(
      {required String url,
      required int concurrency,
      required String output,
      required int retries,
      required int videoBitrate,
      required int audioBitrate,
      required bool keepTemp}) {
    final sink = RustStreamSink<ProgressUpdate>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_StreamSink_progress_update_Sse(sink, serializer);
        sse_encode_String(url, serializer);
        sse_encode_i_32(concurrency, serializer);
        sse_encode_String(output, serializer);
        sse_encode_i_32(retries, serializer);
        sse_encode_i_32(videoBitrate, serializer);
        sse_encode_i_32(audioBitrate, serializer);
        sse_encode_bool(keepTemp, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDownloaderHls2Mp4RunConstMeta,
      argValues: [
        sink,
        url,
        concurrency,
        output,
        retries,
        videoBitrate,
        audioBitrate,
        keepTemp
      ],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiDownloaderHls2Mp4RunConstMeta =>
      const TaskConstMeta(
        debugName: "hls2mp4_run",
        argNames: [
          "sink",
          "url",
          "concurrency",
          "output",
          "retries",
          "videoBitrate",
          "audioBitrate",
          "keepTemp"
        ],
      );

  @override
  Future<void> crateApiDownloaderInitApp() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDownloaderInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDownloaderInitAppConstMeta => const TaskConstMeta(
        debugName: "init_app",
        argNames: [],
      );

  @override
  Future<MediaInspectionResult> crateApiDownloaderInspectMediaFromUrl(
      {required String url}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(url, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_media_inspection_result,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDownloaderInspectMediaFromUrlConstMeta,
      argValues: [url],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDownloaderInspectMediaFromUrlConstMeta =>
      const TaskConstMeta(
        debugName: "inspect_media_from_url",
        argNames: ["url"],
      );

  @override
  Future<MediaInspectionResult> crateApiDownloaderInspectMediaWithContext(
      {required String url, required RequestContext requestContext}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(url, serializer);
        sse_encode_box_autoadd_request_context(requestContext, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_media_inspection_result,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDownloaderInspectMediaWithContextConstMeta,
      argValues: [url, requestContext],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDownloaderInspectMediaWithContextConstMeta =>
      const TaskConstMeta(
        debugName: "inspect_media_with_context",
        argNames: ["url", "requestContext"],
      );

  @override
  Future<MediaSource> crateApiDownloaderMediaSourceDefault() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_media_source,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDownloaderMediaSourceDefaultConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDownloaderMediaSourceDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "media_source_default",
        argNames: [],
      );

  @override
  Future<RequestContext> crateApiDownloaderRequestContextDefault() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_request_context,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDownloaderRequestContextDefaultConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDownloaderRequestContextDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "request_context_default",
        argNames: [],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<ProgressUpdate> dco_decode_StreamSink_progress_update_Sse(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BilibiliQrLogin dco_decode_bilibili_qr_login(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return BilibiliQrLogin(
      url: dco_decode_String(arr[0]),
      key: dco_decode_String(arr[1]),
      cookie: dco_decode_String(arr[2]),
    );
  }

  @protected
  BilibiliQrLoginPoll dco_decode_bilibili_qr_login_poll(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return BilibiliQrLoginPoll(
      state: dco_decode_String(arr[0]),
      cookie: dco_decode_String(arr[1]),
      message: dco_decode_String(arr[2]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  DownloadOptions dco_decode_box_autoadd_download_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_download_options(raw);
  }

  @protected
  MediaCollection dco_decode_box_autoadd_media_collection(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_media_collection(raw);
  }

  @protected
  MediaSource dco_decode_box_autoadd_media_source(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_media_source(raw);
  }

  @protected
  RequestContext dco_decode_box_autoadd_request_context(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_request_context(raw);
  }

  @protected
  DownloadOptions dco_decode_download_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return DownloadOptions(
      concurrency: dco_decode_i_32(arr[0]),
      retries: dco_decode_i_32(arr[1]),
      videoBitrate: dco_decode_i_32(arr[2]),
      audioBitrate: dco_decode_i_32(arr[3]),
      keepTemp: dco_decode_bool(arr[4]),
      subtitleMode: dco_decode_subtitle_mode(arr[5]),
      subtitleValue: dco_decode_String(arr[6]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  HeaderEntry dco_decode_header_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return HeaderEntry(
      name: dco_decode_String(arr[0]),
      value: dco_decode_String(arr[1]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<HeaderEntry> dco_decode_list_header_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_header_entry).toList();
  }

  @protected
  List<MediaCandidate> dco_decode_list_media_candidate(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_media_candidate).toList();
  }

  @protected
  List<MediaCollectionEntry> dco_decode_list_media_collection_entry(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_media_collection_entry)
        .toList();
  }

  @protected
  List<MediaSubtitleTrack> dco_decode_list_media_subtitle_track(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_media_subtitle_track).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MediaCandidate dco_decode_media_candidate(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 22)
      throw Exception('unexpected arr length: expect 22 but see ${arr.length}');
    return MediaCandidate(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      extractor: dco_decode_String(arr[2]),
      pageUrl: dco_decode_String(arr[3]),
      mediaUrl: dco_decode_String(arr[4]),
      mediaFallbackUrls: dco_decode_list_String(arr[5]),
      audioUrl: dco_decode_opt_String(arr[6]),
      audioFallbackUrls: dco_decode_list_String(arr[7]),
      container: dco_decode_String(arr[8]),
      protocol: dco_decode_String(arr[9]),
      mimeType: dco_decode_String(arr[10]),
      qualityLabel: dco_decode_String(arr[11]),
      qualityBadge: dco_decode_String(arr[12]),
      codec: dco_decode_String(arr[13]),
      width: dco_decode_i_32(arr[14]),
      height: dco_decode_i_32(arr[15]),
      requiresFfmpeg: dco_decode_bool(arr[16]),
      score: dco_decode_i_32(arr[17]),
      segmentCount: dco_decode_i_32(arr[18]),
      durationSeconds: dco_decode_f_64(arr[19]),
      primary: dco_decode_bool(arr[20]),
      reason: dco_decode_String(arr[21]),
    );
  }

  @protected
  MediaCollection dco_decode_media_collection(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return MediaCollection(
      kind: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      entries: dco_decode_list_media_collection_entry(arr[2]),
    );
  }

  @protected
  MediaCollectionEntry dco_decode_media_collection_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return MediaCollectionEntry(
      id: dco_decode_String(arr[0]),
      index: dco_decode_i_32(arr[1]),
      title: dco_decode_String(arr[2]),
      durationSeconds: dco_decode_f_64(arr[3]),
      pageUrl: dco_decode_String(arr[4]),
      available: dco_decode_bool(arr[5]),
      unavailableReason: dco_decode_String(arr[6]),
      current: dco_decode_bool(arr[7]),
    );
  }

  @protected
  MediaInspectionResult dco_decode_media_inspection_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return MediaInspectionResult(
      pageUrl: dco_decode_String(arr[0]),
      pageTitle: dco_decode_String(arr[1]),
      extractor: dco_decode_String(arr[2]),
      candidates: dco_decode_list_media_candidate(arr[3]),
      subtitles: dco_decode_list_media_subtitle_track(arr[4]),
      warnings: dco_decode_list_String(arr[5]),
      authRequired: dco_decode_bool(arr[6]),
      challengeReason: dco_decode_String(arr[7]),
      collection: dco_decode_opt_box_autoadd_media_collection(arr[8]),
    );
  }

  @protected
  MediaSource dco_decode_media_source(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return MediaSource(
      pageUrl: dco_decode_String(arr[0]),
      mediaUrl: dco_decode_String(arr[1]),
      mediaFallbackUrls: dco_decode_list_String(arr[2]),
      audioUrl: dco_decode_opt_String(arr[3]),
      audioFallbackUrls: dco_decode_list_String(arr[4]),
    );
  }

  @protected
  MediaSubtitleTrack dco_decode_media_subtitle_track(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return MediaSubtitleTrack(
      language: dco_decode_String(arr[0]),
      label: dco_decode_String(arr[1]),
      url: dco_decode_String(arr[2]),
      selected: dco_decode_bool(arr[3]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  MediaCollection? dco_decode_opt_box_autoadd_media_collection(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_media_collection(raw);
  }

  @protected
  ProgressUpdate dco_decode_progress_update(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ProgressUpdate(
      message: dco_decode_String(arr[0]),
      progress: dco_decode_f_64(arr[1]),
      error: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  RequestContext dco_decode_request_context(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return RequestContext(
      userAgent: dco_decode_String(arr[0]),
      referer: dco_decode_String(arr[1]),
      origin: dco_decode_String(arr[2]),
      cookie: dco_decode_String(arr[3]),
      headers: dco_decode_list_header_entry(arr[4]),
    );
  }

  @protected
  SubtitleMode dco_decode_subtitle_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SubtitleMode.values[raw as int];
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<ProgressUpdate> sse_decode_StreamSink_progress_update_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BilibiliQrLogin sse_decode_bilibili_qr_login(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_url = sse_decode_String(deserializer);
    var var_key = sse_decode_String(deserializer);
    var var_cookie = sse_decode_String(deserializer);
    return BilibiliQrLogin(url: var_url, key: var_key, cookie: var_cookie);
  }

  @protected
  BilibiliQrLoginPoll sse_decode_bilibili_qr_login_poll(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_state = sse_decode_String(deserializer);
    var var_cookie = sse_decode_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    return BilibiliQrLoginPoll(
        state: var_state, cookie: var_cookie, message: var_message);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  DownloadOptions sse_decode_box_autoadd_download_options(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_download_options(deserializer));
  }

  @protected
  MediaCollection sse_decode_box_autoadd_media_collection(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_media_collection(deserializer));
  }

  @protected
  MediaSource sse_decode_box_autoadd_media_source(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_media_source(deserializer));
  }

  @protected
  RequestContext sse_decode_box_autoadd_request_context(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_request_context(deserializer));
  }

  @protected
  DownloadOptions sse_decode_download_options(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_concurrency = sse_decode_i_32(deserializer);
    var var_retries = sse_decode_i_32(deserializer);
    var var_videoBitrate = sse_decode_i_32(deserializer);
    var var_audioBitrate = sse_decode_i_32(deserializer);
    var var_keepTemp = sse_decode_bool(deserializer);
    var var_subtitleMode = sse_decode_subtitle_mode(deserializer);
    var var_subtitleValue = sse_decode_String(deserializer);
    return DownloadOptions(
        concurrency: var_concurrency,
        retries: var_retries,
        videoBitrate: var_videoBitrate,
        audioBitrate: var_audioBitrate,
        keepTemp: var_keepTemp,
        subtitleMode: var_subtitleMode,
        subtitleValue: var_subtitleValue);
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  HeaderEntry sse_decode_header_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_value = sse_decode_String(deserializer);
    return HeaderEntry(name: var_name, value: var_value);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<HeaderEntry> sse_decode_list_header_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <HeaderEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_header_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<MediaCandidate> sse_decode_list_media_candidate(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MediaCandidate>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_media_candidate(deserializer));
    }
    return ans_;
  }

  @protected
  List<MediaCollectionEntry> sse_decode_list_media_collection_entry(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MediaCollectionEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_media_collection_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<MediaSubtitleTrack> sse_decode_list_media_subtitle_track(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MediaSubtitleTrack>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_media_subtitle_track(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MediaCandidate sse_decode_media_candidate(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_extractor = sse_decode_String(deserializer);
    var var_pageUrl = sse_decode_String(deserializer);
    var var_mediaUrl = sse_decode_String(deserializer);
    var var_mediaFallbackUrls = sse_decode_list_String(deserializer);
    var var_audioUrl = sse_decode_opt_String(deserializer);
    var var_audioFallbackUrls = sse_decode_list_String(deserializer);
    var var_container = sse_decode_String(deserializer);
    var var_protocol = sse_decode_String(deserializer);
    var var_mimeType = sse_decode_String(deserializer);
    var var_qualityLabel = sse_decode_String(deserializer);
    var var_qualityBadge = sse_decode_String(deserializer);
    var var_codec = sse_decode_String(deserializer);
    var var_width = sse_decode_i_32(deserializer);
    var var_height = sse_decode_i_32(deserializer);
    var var_requiresFfmpeg = sse_decode_bool(deserializer);
    var var_score = sse_decode_i_32(deserializer);
    var var_segmentCount = sse_decode_i_32(deserializer);
    var var_durationSeconds = sse_decode_f_64(deserializer);
    var var_primary = sse_decode_bool(deserializer);
    var var_reason = sse_decode_String(deserializer);
    return MediaCandidate(
        id: var_id,
        title: var_title,
        extractor: var_extractor,
        pageUrl: var_pageUrl,
        mediaUrl: var_mediaUrl,
        mediaFallbackUrls: var_mediaFallbackUrls,
        audioUrl: var_audioUrl,
        audioFallbackUrls: var_audioFallbackUrls,
        container: var_container,
        protocol: var_protocol,
        mimeType: var_mimeType,
        qualityLabel: var_qualityLabel,
        qualityBadge: var_qualityBadge,
        codec: var_codec,
        width: var_width,
        height: var_height,
        requiresFfmpeg: var_requiresFfmpeg,
        score: var_score,
        segmentCount: var_segmentCount,
        durationSeconds: var_durationSeconds,
        primary: var_primary,
        reason: var_reason);
  }

  @protected
  MediaCollection sse_decode_media_collection(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_entries = sse_decode_list_media_collection_entry(deserializer);
    return MediaCollection(
        kind: var_kind, title: var_title, entries: var_entries);
  }

  @protected
  MediaCollectionEntry sse_decode_media_collection_entry(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_index = sse_decode_i_32(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_durationSeconds = sse_decode_f_64(deserializer);
    var var_pageUrl = sse_decode_String(deserializer);
    var var_available = sse_decode_bool(deserializer);
    var var_unavailableReason = sse_decode_String(deserializer);
    var var_current = sse_decode_bool(deserializer);
    return MediaCollectionEntry(
        id: var_id,
        index: var_index,
        title: var_title,
        durationSeconds: var_durationSeconds,
        pageUrl: var_pageUrl,
        available: var_available,
        unavailableReason: var_unavailableReason,
        current: var_current);
  }

  @protected
  MediaInspectionResult sse_decode_media_inspection_result(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pageUrl = sse_decode_String(deserializer);
    var var_pageTitle = sse_decode_String(deserializer);
    var var_extractor = sse_decode_String(deserializer);
    var var_candidates = sse_decode_list_media_candidate(deserializer);
    var var_subtitles = sse_decode_list_media_subtitle_track(deserializer);
    var var_warnings = sse_decode_list_String(deserializer);
    var var_authRequired = sse_decode_bool(deserializer);
    var var_challengeReason = sse_decode_String(deserializer);
    var var_collection =
        sse_decode_opt_box_autoadd_media_collection(deserializer);
    return MediaInspectionResult(
        pageUrl: var_pageUrl,
        pageTitle: var_pageTitle,
        extractor: var_extractor,
        candidates: var_candidates,
        subtitles: var_subtitles,
        warnings: var_warnings,
        authRequired: var_authRequired,
        challengeReason: var_challengeReason,
        collection: var_collection);
  }

  @protected
  MediaSource sse_decode_media_source(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pageUrl = sse_decode_String(deserializer);
    var var_mediaUrl = sse_decode_String(deserializer);
    var var_mediaFallbackUrls = sse_decode_list_String(deserializer);
    var var_audioUrl = sse_decode_opt_String(deserializer);
    var var_audioFallbackUrls = sse_decode_list_String(deserializer);
    return MediaSource(
        pageUrl: var_pageUrl,
        mediaUrl: var_mediaUrl,
        mediaFallbackUrls: var_mediaFallbackUrls,
        audioUrl: var_audioUrl,
        audioFallbackUrls: var_audioFallbackUrls);
  }

  @protected
  MediaSubtitleTrack sse_decode_media_subtitle_track(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_language = sse_decode_String(deserializer);
    var var_label = sse_decode_String(deserializer);
    var var_url = sse_decode_String(deserializer);
    var var_selected = sse_decode_bool(deserializer);
    return MediaSubtitleTrack(
        language: var_language,
        label: var_label,
        url: var_url,
        selected: var_selected);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  MediaCollection? sse_decode_opt_box_autoadd_media_collection(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_media_collection(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProgressUpdate sse_decode_progress_update(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_message = sse_decode_String(deserializer);
    var var_progress = sse_decode_f_64(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return ProgressUpdate(
        message: var_message, progress: var_progress, error: var_error);
  }

  @protected
  RequestContext sse_decode_request_context(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_userAgent = sse_decode_String(deserializer);
    var var_referer = sse_decode_String(deserializer);
    var var_origin = sse_decode_String(deserializer);
    var var_cookie = sse_decode_String(deserializer);
    var var_headers = sse_decode_list_header_entry(deserializer);
    return RequestContext(
        userAgent: var_userAgent,
        referer: var_referer,
        origin: var_origin,
        cookie: var_cookie,
        headers: var_headers);
  }

  @protected
  SubtitleMode sse_decode_subtitle_mode(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SubtitleMode.values[inner];
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_progress_update_Sse(
      RustStreamSink<ProgressUpdate> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_progress_update,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bilibili_qr_login(
      BilibiliQrLogin self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.url, serializer);
    sse_encode_String(self.key, serializer);
    sse_encode_String(self.cookie, serializer);
  }

  @protected
  void sse_encode_bilibili_qr_login_poll(
      BilibiliQrLoginPoll self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.state, serializer);
    sse_encode_String(self.cookie, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_download_options(
      DownloadOptions self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_download_options(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_media_collection(
      MediaCollection self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_media_collection(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_media_source(
      MediaSource self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_media_source(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_request_context(
      RequestContext self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_request_context(self, serializer);
  }

  @protected
  void sse_encode_download_options(
      DownloadOptions self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.concurrency, serializer);
    sse_encode_i_32(self.retries, serializer);
    sse_encode_i_32(self.videoBitrate, serializer);
    sse_encode_i_32(self.audioBitrate, serializer);
    sse_encode_bool(self.keepTemp, serializer);
    sse_encode_subtitle_mode(self.subtitleMode, serializer);
    sse_encode_String(self.subtitleValue, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_header_entry(HeaderEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.value, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_header_entry(
      List<HeaderEntry> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_header_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_media_candidate(
      List<MediaCandidate> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_media_candidate(item, serializer);
    }
  }

  @protected
  void sse_encode_list_media_collection_entry(
      List<MediaCollectionEntry> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_media_collection_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_media_subtitle_track(
      List<MediaSubtitleTrack> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_media_subtitle_track(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_media_candidate(
      MediaCandidate self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.extractor, serializer);
    sse_encode_String(self.pageUrl, serializer);
    sse_encode_String(self.mediaUrl, serializer);
    sse_encode_list_String(self.mediaFallbackUrls, serializer);
    sse_encode_opt_String(self.audioUrl, serializer);
    sse_encode_list_String(self.audioFallbackUrls, serializer);
    sse_encode_String(self.container, serializer);
    sse_encode_String(self.protocol, serializer);
    sse_encode_String(self.mimeType, serializer);
    sse_encode_String(self.qualityLabel, serializer);
    sse_encode_String(self.qualityBadge, serializer);
    sse_encode_String(self.codec, serializer);
    sse_encode_i_32(self.width, serializer);
    sse_encode_i_32(self.height, serializer);
    sse_encode_bool(self.requiresFfmpeg, serializer);
    sse_encode_i_32(self.score, serializer);
    sse_encode_i_32(self.segmentCount, serializer);
    sse_encode_f_64(self.durationSeconds, serializer);
    sse_encode_bool(self.primary, serializer);
    sse_encode_String(self.reason, serializer);
  }

  @protected
  void sse_encode_media_collection(
      MediaCollection self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.kind, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_list_media_collection_entry(self.entries, serializer);
  }

  @protected
  void sse_encode_media_collection_entry(
      MediaCollectionEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_i_32(self.index, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_f_64(self.durationSeconds, serializer);
    sse_encode_String(self.pageUrl, serializer);
    sse_encode_bool(self.available, serializer);
    sse_encode_String(self.unavailableReason, serializer);
    sse_encode_bool(self.current, serializer);
  }

  @protected
  void sse_encode_media_inspection_result(
      MediaInspectionResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.pageUrl, serializer);
    sse_encode_String(self.pageTitle, serializer);
    sse_encode_String(self.extractor, serializer);
    sse_encode_list_media_candidate(self.candidates, serializer);
    sse_encode_list_media_subtitle_track(self.subtitles, serializer);
    sse_encode_list_String(self.warnings, serializer);
    sse_encode_bool(self.authRequired, serializer);
    sse_encode_String(self.challengeReason, serializer);
    sse_encode_opt_box_autoadd_media_collection(self.collection, serializer);
  }

  @protected
  void sse_encode_media_source(MediaSource self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.pageUrl, serializer);
    sse_encode_String(self.mediaUrl, serializer);
    sse_encode_list_String(self.mediaFallbackUrls, serializer);
    sse_encode_opt_String(self.audioUrl, serializer);
    sse_encode_list_String(self.audioFallbackUrls, serializer);
  }

  @protected
  void sse_encode_media_subtitle_track(
      MediaSubtitleTrack self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.language, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_String(self.url, serializer);
    sse_encode_bool(self.selected, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_media_collection(
      MediaCollection? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_media_collection(self, serializer);
    }
  }

  @protected
  void sse_encode_progress_update(
      ProgressUpdate self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
    sse_encode_f_64(self.progress, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_request_context(
      RequestContext self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.userAgent, serializer);
    sse_encode_String(self.referer, serializer);
    sse_encode_String(self.origin, serializer);
    sse_encode_String(self.cookie, serializer);
    sse_encode_list_header_entry(self.headers, serializer);
  }

  @protected
  void sse_encode_subtitle_mode(SubtitleMode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
